# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 1b48c6bb535e8972e5b090965b9717360070154f6efa4bc4559957ba4b9b34d9480cc83f28d79780e55a9a77080a27557d5f0c2890b0e854bc184380d002be13

test:
  domain_name: example.com 
  secret_key_base: 5e9cf28fd9eef8f95f5f0e82ab3dbc3b352ae87e9e576c1562bb04d738dd5a0c71eb658332502cadbf4156c93ebf6be8adc2493bd2047a54321236040876d1c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
